server:
  tomcat:
    basedir: /var/tmp/website-blog-admin
spring:
  profiles:
    include:
    - center-dev
  mail:
    default-encoding: UTF-8
    protocol: smtp
    host: xxx
    port: 465
    username: xxx
    password: xxx
    test-connection: false
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.port: 465
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 50000
      mail.smtp.timeout: 30000
      mail.smtp.writetimeout: 50000
  redis:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 5000ms
    expire: 2592000
logging:
  path: /var/tmp/website-blog-admin
app:
  enableKaptcha: false
  enabledConfigLog: true
  shiro:
    loginUrl: /passport/login/
    successUrl: /
    unauthorizedUrl: /error/403