spring:
  profiles:
    include: [center]
  ####### database Config #######
  datasource:
    druid:
      connection-init-sqls: set names utf8mb4
      driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://39.106.75.107:3306/dblog?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: xiaofeiali
    password: xiaobaoali
  ####### Redis Config #######
  redis:
    database: 6
    # Redis服务器地址
    host: 39.106.75.107
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 

  ####### redis缓存服务配置 #######
  session:
    store-type: redis

  ####### 自定义配置 #######

  ####### 自定义配置 #######
